fastlane_version "2.59.0"

# This app is built for iOS
default_platform :ios

platform :ios do
  before_all do
        
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    gym
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym
    deliver(force: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
